config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  get 'search', action: :search, controller: 'search'

  concern :voted do
    member do
      patch :like
      patch :dislike
    end
  end

  concern :commented do
    member do
      post :comment
    end
  end

  devise_scope :user do
    post 'send_email_confirmation', to: 'oauth_callbacks#send_email_confirmation',
                                    as: :send_email_confirmation
    get 'email_confirmation/:token', to: 'oauth_callbacks#email_confirmation',
                                     as: :email_confirmation
  end

  resources :questions, concerns: %i[voted commented] do
    resources :answers, concerns: %i[voted commented], shallow: true, except: %i[index] do
      patch 'update_best', on: :member
    end
    
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :votes, only: :destroy
  resources :badges, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
        get :all, on: :collection
      end

      resources :questions, except: [:edit, :new] do
        resources :answers, except: [:edit, :new], shallow: true
      end
    end
  end

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :author, class_name: 'User'
  belongs_to :best_answer, class_name: 'Answer', optional: true

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscriptions, dependent: :destroy

  has_one :badge, dependent: :destroy

  has_many_attached :files, dependent: :destroy

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :badge, reject_if: :all_blank

  validates :title, :body, presence: true

  after_create :calculate_reputation

  def common_answers
    answers.where.not(id: best_answer_id)
  end

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end
end

app/controllers/api/v1/questions_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class QuestionsController < Api::V1::BaseController
      protect_from_forgery with: :null_session, prepend: true

      before_action :find_question, only: %i[show destroy update]
      load_and_authorize_resource

      def index
        respond_with @questions, each_serializer: QuestionSerializer
      end

      def show
        respond_with @question, serializer: QuestionSerializer
      end

      def create
        @question = current_resource_owner.questions.create(question_params)

        if @question.save
          render json: @question, serializer: QuestionSerializer, status: :created
        else
          render json: { errors: @question.errors }, status: :unprocessable_entity
        end
      end

      def update
        if @question.update(question_params)
          render json: @question, serializer: QuestionSerializer, status: :accepted
        else
          render json: { errors: @question.errors }, status: :unprocessable_entity
        end
      end

      def destroy
        @question.destroy
        render json: { messages: ['Question deleted'] }
      end

      private

      def question_params
        params.require(:question).permit(:title, :body)
      end

      def find_question
        @question = Question.find(params[:id])
      end
    end
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show update destroy]
  before_action :find_subsription, only: [:show]

  after_action :publish, only: [:create]

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answers = @question.answers
    @answer = Answer.new
    @answer.links.new
    gon.push({ question_id: @question.id })
  end

  def new
    @question = Question.new
    @question.links.new
    @question.build_badge
  end

  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'Question was successfully deleted.'
  end

  private

  def publish
    return if @question.errors.any?

    @question.subscriptions.create!(user: current_user)

    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/question_partial',
        locals: { question: @question }
      )
    )
  end

  def question_params
    params.require(:question).permit(:title, :body, :author_id, files: [], links_attributes: %i[name url],
                                                                badge_attributes: %i[name image])
  end

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def find_subsription
    @subscription = @question.subscriptions.find_by(user: current_user)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_link_fields.html.slim
div class="nested-fields"
  p= f.label :name, 'Link Name'
  = f.text_field :name

  p= f.label :url, 'Link Url'
  = f.text_field :url
  
  p
  = link_to_remove_association "remove link", f

app/views/questions/_question.html.slim
.question
  tr     
    p= question.body
    .subscription
      td= render 'subscriptions/subscription', resource: question
    - if can? :destroy, question
      td= link_to 'Delete Question', question, method: :delete, class: 'btn btn-sm btn-outline-primary mt-2'
    - if can? :update, question  
      td= link_to 'Edit Body', '#', class: 'edit-question-link', data: { question_id: question.id }, class: 'question-edit-body-button btn btn-sm btn-outline-primary mt-2'
      td= form_with model: question, local: false, class: 'hidden', html: { id:"edit-question-#{question.id}" } do |f|
        p= f.label :body, 'Question'
        p= f.text_area :body
        p= f.label :files
        p= f.file_field :files, multiple: true
        p Links: 
        div class="Question links"
          = f.fields_for :links do |l|
            = render 'link_fields', f: l
        div class="links"  
          = link_to_add_association 'add link', f, :links 
        p= f.submit 'Save Question'
    - if question.files.attached?
      p Attached Files:
      table
        - question.files.each do |file|
            tr class="file-#{file.id}"
              td= link_to file.filename.to_s, url_for(file)
              - if can? :destroy, file
                td |
                td= link_to 'Remove', attachment_path(file.id), remote: true, method: :delete
    td.question-comment-block
      button.question-new-comment-button.btn.btn-sm.btn-outline-primary.mt-2 type="button" Comment
    
    
    p Links:
    div class="question_links"
      table
        - question.links.each do |link|
          tr class="link-#{link.id}"
          - if link.is_a_gist?
            td class="link-script"= link_to open(link.url + '.txt').read, link.url
          - else
            td= link_to link.name, link.url
          - if can? :destroy, link
            td= link_to 'Remove',link_path(link.id), remote: true, method: :delete

    .question-comments     
      p Comments
      = render question.comments
    div id="question-new-comment" class="hidden"
      = render 'shared/comment', resource: question
      

app/views/questions/_question_partial.slim
tr
  td.question = link_to question.title, question
  td= render 'shared/vote', resource: question

app/views/questions/index.html.slim
.col-12.col-md-8.offset-1
  =link_to 'Ask question', new_question_path, class: 'btn btn-primary mt-2'
  table.table
    thead
      tr
        th Question
        th Voting
        th Rating
    - cache collection_cache_key_for :question do
      - @questions.each do |question|
        tr
          td.question = link_to question.title, question
          - if can? :like, question
            td= render 'shared/vote', resource: question

app/views/questions/new.html.slim
.col-12.col-md-8.offset-1
  div class="mx-auto"
    .question-errors
      = render 'shared/errors', resource: @question

    = form_with model: @question do |f|
      p= f.label :title
      = f.text_field :title

      p= f.label :body
      = f.text_area :body

      p= f.label :files
      = f.file_field :files, multiple: true
        
      p Links: 
      div class="Question links"
        = f.fields_for :links do |l|
          = render 'link_fields', f: l

      div class="links"  
        p= link_to_add_association 'add link', f, :links 
          
      p Awards: 
      div class="Question rewards"
        = f.fields_for :badge do |a|
          p= a.label :name, 'Badge title'
          = a.text_field :name
          p= a.label :image
          = a.file_field :image

      p= f.submit 'Ask', class: 'btn btn-primary mt-2'

app/views/questions/show.html.slim
- cache @question do
  .col-12.col-md-8.offset-1
    h1= @question.title
    .question-errors
      = render 'shared/errors', resource: @question
    = render @question

    .answers
      p.p.mt-2 The Best
      table.table.best_answer
        = render @question.best_answer if @question.best_answer.present?

      p Other
      table.table.common_answers
        = render @question.common_answers
        
    .answer-errors
      = render 'shared/errors', resource: @answer
    .new-answer
      button.new-answer-button.btn.btn-primary.mt-2 type="button" New answer
      div id="new-answer-block" class="hidden"
        = form_with model: [@question, @answer], local: false, class: 'new-answer' do |f|
          p= f.label :body, 'Answer'
          p= f.text_area :body, class: 'form-control'
          p= f.label :files
          p= f.file_field :files, multiple: true
          
          .new-answer-links
            button.new-answer-links-button.btn.btn-primary.mt-2 type="button" Add links
            div id="new-answer-links-block" class="hidden"
              div class="Question links"
                = f.fields_for :links do |l|
                  = render 'link_fields', f: l

                div class="links"  
                  = link_to_add_association 'add link', f, :links 

          p= f.submit 'Send answer', class: 'btn btn-primary mt-2'

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');
<% if !@question.errors.present? %>
  $('.question').html('<%= j render @question %>');
<% end %>