config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  get 'search', action: :search, controller: 'search'

  concern :voted do
    member do
      patch :like
      patch :dislike
    end
  end

  concern :commented do
    member do
      post :comment
    end
  end

  devise_scope :user do
    post 'send_email_confirmation', to: 'oauth_callbacks#send_email_confirmation',
                                    as: :send_email_confirmation
    get 'email_confirmation/:token', to: 'oauth_callbacks#email_confirmation',
                                     as: :email_confirmation
  end

  resources :questions, concerns: %i[voted commented] do
    resources :answers, concerns: %i[voted commented], shallow: true, except: %i[index] do
      patch 'update_best', on: :member
    end
    
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :votes, only: :destroy
  resources :badges, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
        get :all, on: :collection
      end

      resources :questions, except: [:edit, :new] do
        resources :answers, except: [:edit, :new], shallow: true
      end
    end
  end

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/views/shared/_comment.html.slim
.new-comment-form
  = form_with scope: :comment, url: polymorphic_path(resource, action: :comment), local: false  do |f|
    p= f.text_area :body, class: 'form-control mt-2', id: 'comment_body'
    p= f.submit 'Add comment', class: 'btn btn-primary mt-2'

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_link_fields.html.slim
div class="nested-fields"
  = f.label :name, 'Link Name'
  = f.text_field :name

  = f.label :url, 'Link Url'
  = f.text_field :url

  = link_to_remove_association "remove link", f

app/views/shared/_nav.html.slim
nav.navbar.navbar-light.bg-light
  span.navbar-text
    - if user_signed_in?
      a= link_to 'Questions', questions_path
      a= link_to 'My Awards', badges_path
      a= link_to 'Sign out', destroy_user_session_path, method: :delete
    - else 
      = link_to 'Sign in', new_user_session_path
      = link_to 'Registration', new_user_registration_path

.search
  = form_with url: search_path, local: true, method: :get do |f|
    .d-flex
      = f.text_field :body, class: 'mr-sm-2 form-control'
      = f.select :type, SearchService::TYPES, class: 'form-control'
      = f.submit 'Search', class: 'btn btn-outline-success mx-3'

app/views/shared/_vote.html.slim
.vote
  =link_to 'Like', polymorphic_path(resource, action: :like), method: :patch, data: { type: :json}, remote: true, class: 'btn btn-sm btn-outline-primary mt-2'
  =link_to 'Dislike', polymorphic_path(resource, action: :dislike), method: :patch, data: { type: :json}, remote: true, class: 'btn btn-sm btn-outline-primary mt-2'
td.rating id= "rating-#{resource.class.name.downcase}-#{resource.id}" = resource.rating 