config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  get 'search', action: :search, controller: 'search'

  concern :voted do
    member do
      patch :like
      patch :dislike
    end
  end

  concern :commented do
    member do
      post :comment
    end
  end

  devise_scope :user do
    post 'send_email_confirmation', to: 'oauth_callbacks#send_email_confirmation',
                                    as: :send_email_confirmation
    get 'email_confirmation/:token', to: 'oauth_callbacks#email_confirmation',
                                     as: :email_confirmation
  end

  resources :questions, concerns: %i[voted commented] do
    resources :answers, concerns: %i[voted commented], shallow: true, except: %i[index] do
      patch 'update_best', on: :member
    end
    
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :votes, only: :destroy
  resources :badges, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
        get :all, on: :collection
      end

      resources :questions, except: [:edit, :new] do
        resources :answers, except: [:edit, :new], shallow: true
      end
    end
  end

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :author, class_name: 'User'

  has_many_attached :files, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  after_create :send_notification

  private

  def send_notification
    NotificationsJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!, except: [:show]
  before_action :find_question, only: %i[new create]
  before_action :load_answer, only: %i[show destroy update update_best]

  after_action :publish, only: [:create]

  authorize_resource :answer, through: :question, shallow: true,
                              only: %i[create edit update destroy toggle_best]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.create(answer_params)
  end

  def update
    @answer.update(answer_params)
  end

  def destroy
    @answer.destroy
  end

  def update_best
    MarkBestAnswerService.call(@answer)
  end

  private

  def publish
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "answer_question_#{params[:question_id]}",
      ApplicationController.render_with_signed_in_user(
        current_user,
        partial: 'answers/answer',
        locals: { answer: @answer }
      )
    )
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[name url]).merge(author: current_user)
  end
end

app/controllers/api/v1/answers_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class AnswersController < Api::V1::BaseController
      load_and_authorize_resource

      def show
        respond_with @answer, serializer: AnswerShowSerializer
      end

      def create
        @answer = current_resource_owner.answers.create(answer_params.merge(question_id: params[:question_id]))

        if @answer.save
          render json: @answer, serializer: AnswerShowSerializer, status: :created
        else
          render json: { errors: @answer.errors }, status: :unprocessable_entity
        end
      end

      def update
        @answer.update(answer_params)

        respond_with @answer, serializer: AnswerShowSerializer
      end

      def destroy
        @answer.destroy

        render json: { messages: ['Answer deleted'] }
      end

      private

      def answer_params
        params.require(:answer).permit(:body)
      end
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache answer do
  tr class="answer-#{answer.id}"
    td.body = answer.body
    - if can? :destroy, answer
      td = link_to "Delete Answer", answer, remote: true, method: :delete, class: 'btn btn-sm btn-outline-primary mt-2'
    - if can? :update, answer
      td = link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }, class: 'answer-edit-button btn btn-sm btn-outline-primary mt-2'
      td= form_with model: answer, local: false, class: 'hidden', html: { id:"edit-answer-#{answer.id}" } do |f|
        p= f.label :body, 'Answer'
        p= f.text_area :body
        p= f.file_field :files, multiple: true

        p Links: 
        div class="Question links"
          = f.fields_for :links do |l|
            = render 'shared/link_fields', f: l
        div class="links"  
          = link_to_add_association 'add link', f, :links , class: 'btn btn-sm btn-outline-primary mt-2'

        p= f.submit 'Save Answer', class: 'btn btn-sm btn-outline-primary mt-2'
    - if can? :update_best, answer
      td = link_to "Mark Best", update_best_answer_path(answer), remote: true, method: :patch, class: 'btn btn-sm btn-outline-primary mt-2'
    - if answer.files.attached?
      - answer.files.each do |file|
            td class="file-#{file.id}"= link_to file.filename.to_s, url_for(file)
            - if can? :destroy, file
              td class="file-#{file.id}"= link_to 'Remove', attachment_path(file.id), remote: true, method: :delete
    td Links:
    - answer.links.each do |link|
      - if link.is_a_gist?
        td class="link-script"= link_to open(link.url + '.txt').read, link.url
      - else
        td class="link-#{link.id}"= link_to link.name, link.url
      - if can? :destroy, link
        td class="link-#{link.id}"= link_to 'Remove',link_path(link.id), remote: true, method: :delete

    - if answer.best_flag == true && answer.question.badge.present?
      td Award:
      td= answer.question.badge.name
      td= image_tag(answer.question.badge.image , size: "50x50")
    td = render 'shared/vote', resource: answer

    td= render 'shared/comment', resource: answer

    td Answer Comments
    td class="answer-#{answer.id}-comments"
      = render answer.comments

app/views/answers/destroy.js.erb
  $('.answer-<%= @answer.id%>').remove();

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');
<% if !@answer.errors.present? %>
  $('.answer-<%= @answer.id%>').html('<%= j render @answer %>');
<% end %>

app/views/answers/update_best.js.erb
$('.answer-<%= @answer.id%>').remove();
$('.best_answer').children().eq(0).detach().appendTo('.common_answers')
$('.best_answer').html('<%= j render @answer %>');