config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  get 'search', action: :search, controller: 'search'

  concern :voted do
    member do
      patch :like
      patch :dislike
    end
  end

  concern :commented do
    member do
      post :comment
    end
  end

  devise_scope :user do
    post 'send_email_confirmation', to: 'oauth_callbacks#send_email_confirmation',
                                    as: :send_email_confirmation
    get 'email_confirmation/:token', to: 'oauth_callbacks#email_confirmation',
                                     as: :email_confirmation
  end

  resources :questions, concerns: %i[voted commented] do
    resources :answers, concerns: %i[voted commented], shallow: true, except: %i[index] do
      patch 'update_best', on: :member
    end
    
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :votes, only: :destroy
  resources :badges, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
        get :all, on: :collection
      end

      resources :questions, except: [:edit, :new] do
        resources :answers, except: [:edit, :new], shallow: true
      end
    end
  end

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/subscription.rb
# frozen_string_literal: true

class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/controllers/subscriptions_controller.rb
# frozen_string_literal: true

class SubscriptionsController < ApplicationController
  before_action :authenticate_user!

  load_resource :question
  load_and_authorize_resource :subscription, through: :question, shallow: true

  def create
    @question = Question.find(params[:question_id])
    @subscription = @question.subscriptions.create(user: current_user)
  end

  def destroy
    @subscription = current_user.subscriptions.find(params[:id])
    @subscription.destroy
  end
end

app/views/subscriptions/_subscription.html.slim
- if current_user&.subscribed?(resource)
  = link_to 'Unsubscribe', subscription_path(@subscription.id), method: :delete, remote: true, class: 'btn btn-sm btn-outline-primary mt-2'
- elsif current_user
  = link_to 'Subscribe', question_subscriptions_path(resource), method: :post, remote: true, class: 'btn btn-sm btn-outline-primary mt-2'

app/views/subscriptions/create.js.erb
$('.subscription').html('<%= j render 'subscriptions/subscription', resource: @question %>');

app/views/subscriptions/destroy.js.erb
$('.subscription').html('<%= j render 'subscriptions/subscription', resource: @subscription.question %>');